//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NlpDroneControl
{
    [Serializable]
    public class ExecuteDroneActionRequest : Message
    {
        public const string k_RosMessageName = "nlp_drone_control/ExecuteDroneAction";
        public override string RosMessageName => k_RosMessageName;

        //  --- Request ---
        //  动作的类型，例如 "adjust_camera", "rotate_360", "hover_and_monitor"
        public string action_type;
        //  (可选) 动作的参数，我们可以用一个JSON字符串来灵活地传递
        //  例如：对于adjust_camera, params可以是 "{\"pitch_angle\": -90.0}"
        //  对于hover_and_monitor, params可以是 "{\"duration_seconds\": 5.0}"
        public string params_json;

        public ExecuteDroneActionRequest()
        {
            this.action_type = "";
            this.params_json = "";
        }

        public ExecuteDroneActionRequest(string action_type, string params_json)
        {
            this.action_type = action_type;
            this.params_json = params_json;
        }

        public static ExecuteDroneActionRequest Deserialize(MessageDeserializer deserializer) => new ExecuteDroneActionRequest(deserializer);

        private ExecuteDroneActionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action_type);
            deserializer.Read(out this.params_json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_type);
            serializer.Write(this.params_json);
        }

        public override string ToString()
        {
            return "ExecuteDroneActionRequest: " +
            "\naction_type: " + action_type.ToString() +
            "\nparams_json: " + params_json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
