//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NlpDroneControl
{
    [Serializable]
    public class ExecuteDroneActionResponse : Message
    {
        public const string k_RosMessageName = "nlp_drone_control/ExecuteDroneAction";
        public override string RosMessageName => k_RosMessageName;

        //  --- Response ---
        public bool success;
        //  动作是否成功执行
        public string message;
        //  返回给LLM的信息，例如 "Camera adjusted." 或 "Rotation failed."

        public ExecuteDroneActionResponse()
        {
            this.success = false;
            this.message = "";
        }

        public ExecuteDroneActionResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static ExecuteDroneActionResponse Deserialize(MessageDeserializer deserializer) => new ExecuteDroneActionResponse(deserializer);

        private ExecuteDroneActionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ExecuteDroneActionResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
